name: Merge develop and set up Python
description: 'Merge develop into current branch, and set up Python'
runs:
  using: composite
  steps:
    - name: Merge develop branch into the current branch
      uses: ./.github/actions/merge
    - name: Setup Python 3.9.20
      uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: '3.9.20'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: |
          requirements_dev.txt
    - name: Show whether a cache hit occurred (for debugging purposes).
      run: |
        echo "${{ steps.setup_python.outputs.cache-hit }}"
      shell: bash
    - name: Install third-party Python dev dependencies
      uses: nick-fields/retry@v3
      with:
        max_attempts: 3
        retry_on: error
        shell: bash
        timeout_minutes: 30
        # Note that the effects of this don't seem to be cached by setup-python,
        # resulting in the occasional "No module named PIL" errors in CI.
        command: python -m scripts.install_python_dev_dependencies
    - name: Show where pip installs its packages.
      run: |
        pip show certifi
      shell: bash
