name: Checks CI Test Suites To Run
description: Computes which CI test suites to run
inputs:
  event_name:
    required: true
    type: string
  pr_base_ref:
    required: true
    type: string
  # This is set as a repository-level variable and passed in from the GitHub
  # Actions workflow.
  # See https://github.com/oppia/oppia/settings/variables/actions
  run_suites_on_changed_files:
    required: true
    type: string
outputs:
  test_suites_to_run:
    value: ${{ steps.check_test_suites_to_run.outputs.TEST_SUITES_TO_RUN }}

runs:
  using: 'composite'
  steps:
    - id: check_test_suites_to_run
      name: Check test suites to run
      # This prints to stdout and also writes the output to ./suites-to-run.json.
      env:
        SHOULD_OUTPUT_ALL_TESTS: ${{ inputs.event_name != 'pull_request' || inputs.run_suites_on_changed_files == 'false' }}
      run: >
        echo "TEST_SUITES_TO_RUN=";
        python -m scripts.check_ci_test_suites_to_run
        --github_head_ref="HEAD"
        --github_base_ref="origin/${{ inputs.pr_base_ref }}"
        ${{ env.SHOULD_OUTPUT_ALL_TESTS == 'true' && '--output_all_test_suites' || '' }} | tee ./suites-to-run.json
      shell: bash
    - name: Upload suites-to-run mapping as a GitHub artifact
      uses: actions/upload-artifact@v4
      with:
        name: suites-to-run
        path: suites-to-run.json
    - name: Upload root files mapping as a GitHub artifact
      uses: actions/upload-artifact@v4
      with:
        name: root-files-mapping
        path: root-files-mapping.json
