name: Assign Reviewers on PR Creation for New Contributors

on:
  pull_request:
    types: [opened]  

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Reviewers and Check for Merged PRs
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request, repository } = context.payload;
            const owner = repository.owner.login;
            const repo = repository.name;
            const prNumber = pull_request.number;
            const username = pull_request.user.login;

            // Fetch all closed PRs of the user
            const userPRs = await github.pulls.list({
              owner,
              repo,
              state: "closed",
              per_page: 100,  
              sort: "created",
              direction: "desc",
            });

            const mergedPRs = userPRs.data.filter(pr => pr.merged_at);

            // Check if the user has 0 merged PRs
            const hasZeroMergedPR = mergedPRs.length === 0;

            if (hasZeroMergedPR) {
              console.log(`User @${username} has no merged PRs. Proceeding with reviewer assignment.`);

              // Get requested reviewers from CODEOWNERS
              const requestedReviewers = pull_request.requested_reviewers.map(r => r.login);
              const requestedTeams = pull_request.requested_teams.map(t => t.slug);

              if (requestedReviewers.length > 0) {
                // Assign reviewers from CODEOWNERS as assignees
                await github.issues.addAssignees({
                  owner,
                  repo,
                  issue_number: prNumber,
                  assignees: requestedReviewers,
                });
                console.log(`Assigned reviewers: ${requestedReviewers.join(", ")}`);

                // Notify assigned reviewers
                const commentBody = `Hello @${username}! Thank you for making a PR. Please make sure that your PR is assigned to the correct reviewers -- check the "Assignees" section in the sidebar on the right. Typically, this should match the "Reviewers" section. If it is not correct, you can leave a comment with the syntax \`@reviewer_username PTAL\` to request that a specific reviewer be assigned.\n\n Thanks!`;

                await github.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: commentBody,
                });
              } else {
                // Notify the team if no individual reviewers were found
                console.log("No reviewers found in CODEOWNERS. Notifying team.");
                await github.issues.createComment({
                  owner,
                  repo,
                  issue_number: prNumber,
                  body: `No individual reviewers were found by GitHub. Please assign an appropriate reviewer. @oppia/dev-workflow-reviewers, could you please review the issue? Thank you!`,
                });
              }

              if (requestedTeams.length > 0) {
                console.log(`Teams requested for review: ${requestedTeams.join(", ")}`);
              }
            } else {
              console.log(`User @${username} has merged PRs. Skipping reviewer assignment.`);
            }
