name: Image Compression Check
permissions: 
  contents : write
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop 
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  run_compression:
    name: Run Image Compression Checks
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  
          token: ${{ secrets.BOT_TOKEN }}  

      - name: Setup Python 3.9.20
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.20'
          architecture: 'x64'

      - name: Install GraphicsMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y graphicsmagick
      
      - name: Add GraphicsMagick to PATH
        run: echo "$(dirname $(which gm))" >> $GITHUB_PATH

      - name: Merge develop branch into the current branch
        uses: ./.github/actions/merge

      - name: Initialize Containers
        run: |
          make build
          make stop

      - name: Run Image Compression Check
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        id: compression
        run: |
          make image_compression_check
          echo "::set-output name=changes_made::$(git status --porcelain | grep -c "M" || echo "0")"

      - name: Commit and push if images were compressed
        if: steps.compression.outputs.changes_made != '0'
        run: |
          git config --local user.email "bot@oppia.org"
          git config --local user.name "Oppia Bot"
          git add -A
          git commit -m "chore: Compress images via CI
          Automated image compression to optimize file sizes.
          This commit was automatically generated by the CI workflow." --no-verify
          git fetch origin ${{ github.head_ref }}
          git rebase origin/${{ github.head_ref }}
          git push -u origin feat#21274 --no-verify
          
      - name: Comment on PR
        if: steps.compression.outputs.changes_made != '0' && github.event_name == 'pull_request'
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          curl -X POST \
            -H "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            -d '{"body":"🤖 I have compressed some images in this PR to optimize file sizes. The changes have been automatically committed. Please review the changes and make sure everything looks correct."}'
        
      - name: Report failure if compression fails on develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "Image compression check failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
