name: Broadcast 'push to develop' event to our release-scripts repo
on:
  # Note that status event is triggered when the status of a commit changes
  # on the develop branch.
  # See https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#status
  status

jobs:
  send_notification:
    name: Send notification
    runs-on: ubuntu-22.04
    # Only broadcast this if the status event of a commit on develop branch
    # is successful and the repository is oppia/oppia.
    # Further checks to ensure that the relevant commit can be deployed (e.g.
    # the commit is not an older commit than the latest deployed commit.) is
    # done in the build_release_candidate script.
    if: ${{ (github.repository == 'oppia/oppia') && (github.event.state == 'success') }}
    steps:
      - name: Set environment variables
        id: set_env
        run: |
          echo "VERSION=auto-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        shell: bash
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.NOTIFICATIONS_TOKEN_GENERATOR_GH_APP_ID }}
          private_key: ${{ secrets.NOTIFICATIONS_TOKEN_GENERATOR_GH_APP_PRIVATE_KEY }}
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@87c5425cae5ba8b5bc7da27674076c78588babf3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: oppia/release-scripts
          event-type: develop-commit
          client-payload: '{
            "version": "${{ env.VERSION }}",
            "app_name": "oppiatestserver",
            "maintenance_mode": "false",
            "sha": "${{ github.sha }}",
            "build_was_manually_triggered": "false",
            "repo_owner": "${{ github.repository_owner }}"
          }'
